### ISSUE TITLE
help to compile and try

### ISSUE THREAD

**Issue by vitormicillo** [Baloneo/NetAssistant#1]
It's not a problem, but could you perhaps indicate the dependencies to install, so that the compiler doesn't give an error?
I've tried to include manually with:
```
go get github.com/gotk3/gotk3/gtk
go get github.com/gotk3/gotk3/pango
```
but I always get stuck here
<img width="771" alt="image" src="https://github.com/byte-voyager/NetAssistant/assets/1921806/678d96f1-6545-4b2e-941b-2214be5ae5b3">

**Comment by byte-voyager** [comment]
Maybe you can check the gotk3 installation documentation: https://github.com/gotk3/gotk3/wiki/Installing-on-Linux

**Comment by vitormicillo** [comment]
Thanks mate, it works now 👍🏻
